### ISSUE TITLE
callContractors.lua:117

### ISSUE THREAD

**Issue by Gonimy-Vetrom** [Royal-Modding/FS19_CallContractors#6] opened 2021-04-11 10:56 UTC
`Error: E:/FARMING_SIMULATOR/mods/FS19_CallContractors/callContractors.lua:117: attempt to index field 'contractsManager' (a nil value)`
Tell me, what can it be connected with? Where to seek the cause?
The game launched on my old savegame of modmap.
I also have a lot of mods in mod-folder :)

**Comment by Gonimy-Vetrom** [comment] 2021-04-11 11:15
It seems mod BetterContracts by Emperor of Modding stopped working.

**Comment by TyKonKet** [comment] 2021-04-11 12:50
Can you please send me the full log file, would be great if you could delete it, start the game and reproduce the issue, so that I have to read only pertinent logs.

**Comment by Gonimy-Vetrom** [comment] 2021-04-11 13:54
[log.txt](https://github.com/Royal-Modding/FS19_CallContractors/files/6291928/log.txt)

**Comment by Gonimy-Vetrom** [comment] 2021-04-11 14:25
To start working BetterContracts I had to delete FS19_MapObjectShider :(

**Comment by TyKonKet** [comment] 2021-04-11 14:43
Ok, but without logs or errors I can't find the issue :D

**Comment by Gonimy-Vetrom** [comment] 2021-04-11 15:03
Okay. Now I will try again.
[log.txt](https://github.com/Royal-Modding/FS19_CallContractors/files/6292055/log.txt)
But so far a new error!
I play with the Seasons and now is not time for sowing. But still decided to look, who can sow me and got an error which at the end of the log.

**Comment by Gonimy-Vetrom** [comment] 2021-04-11 15:08
[log.txt](https://github.com/Royal-Modding/FS19_CallContractors/files/6292087/log.txt)
And now a log with an error from MapObjectShider

**Comment by TyKonKet** [comment] 2021-04-12 08:49
Hi @Gonimy-Vetrom, It looks like I've found the issue, both mods needs to be updated to fix it, we still need to perform some tests but as soon as the new releases will be ready I'll let you know here.
Meanwhile thanks a lot for the report, you helped us find a big issue!

**Comment by TyKonKet** [comment] 2021-04-12 09:56
@Gonimy-Vetrom
Here we are, please download the latest versions of both mods and let us know (everything should be fixed).
https://github.com/Royal-Modding/FS19_CallContractors/releases/tag/1.0.0.0-RC2
https://github.com/Royal-Modding/FS19_MapObjectsHider/releases/tag/1.2.0.0-RC2

**Comment by Gonimy-Vetrom** [comment] 2021-04-12 13:43
[log.txt](https://github.com/Royal-Modding/FS19_CallContractors/files/6297107/log.txt)
![fsScreen_2021_04_12_16_40_28](https://user-images.githubusercontent.com/8200153/114403994-f5c66700-9bad-11eb-99c2-e25611250357.png)
Error with the "Selling" tab still remains. :(

**Comment by TyKonKet** [comment] 2021-04-12 13:46
Ok, are other issues fixed?
Can you please give me more info about the silos you are using?

**Comment by Gonimy-Vetrom** [comment] 2021-04-12 13:53
`Error: E:/FARMING_SIMULATOR/mods/FS19_CallContractors/callContractors.lua:117: attempt to index field 'contractsManager' (a nil value)` there is no more this error.

I have only storage on the ground and https://www.farming-simulator.com/mod.php?lang=de&country=at&mod_id=140589

**Comment by TyKonKet** [comment] 2021-04-12 14:05
Ok, I think I know what's happening here.
Anyway i should probably be able to fix the error, but selling will always support only default storages and not strange scripted storages or heaps, at least for te moment.

**Comment by TyKonKet** [comment] 2021-04-12 16:59
@Gonimy-Vetrom 
It should be fixed now, please give it a try as soon as you can and let me know.
https://github.com/Royal-Modding/FS19_CallContractors/releases/tag/1.0.0.0-RC3

**Comment by Gonimy-Vetrom** [comment] 2021-04-12 17:14
Thank you. Now there are no errors. How not and tabs with the sale of goods. It should be?

**Comment by TyKonKet** [comment] 2021-04-12 17:29
The selling tab will appear if you will buy a common silo, at the moment I'm not able to handle scripted silos such as the storage system from vertex.

**Closed by TyKonKet** 2021-04-12 17:29 UTC
Labels: bug
